### ISSUE TITLE
[question] workspace records crawled/included?

### ISSUE THREAD

**Issue by medarob** [schliesser/sitecrawler#10]
Hi,

I have 2 questions about the results:

I ran the sitecrawler and got some errors at the end:
```
Found 78 url(s) in 3 sitemap(s)
...
78/78 [============================] 100% Finished with some errors!
1633234397666: Unable to fetch url: "https://www.domain.tld/neuigkeiten/artikel"
1633234397666: Unable to fetch url: "https://www.domain.tld/veranstaltungen/details"
1633234397666: Unable to fetch url: "https://www.domain.tld/veranstaltungen/details-dummy"
1633234397666: Unable to fetch url: "https://www.domain.tld/neuigkeiten/artikel/7960"
1633234397666: Unable to fetch url: "https://www.domain.tld/veranstaltungen/details/14799"
```
1. question:
The first 3 pages are detail pages for news (ext:news) and events (ext:sf_event_mgt) - not sure if I can omit them from being crawled?
Without an ID there is only the message shown "Dieser Artikel ist nicht mehr verfügbar.". I'm not sure why that results in an error? It's not our typical 404-error page.

2. question:
The last two pages, where the slug is just the (news/event) record ID, exists in workspaces.

The news records with the ID 7960 has the following database entries:
![grafik](https://user-images.githubusercontent.com/33951787/165124341-1c25ff24-4116-43ea-aca2-9d154d4faea9.png)

It also seems that the event record 14799 was also created in workspaces:
![grafik](https://user-images.githubusercontent.com/33951787/165124945-8049b6e9-50b1-46ec-8de4-ddd53733ef01.png)

Is it possible that records (and/or pages?) created in workspaces (t3ver_wsid != 0) are not crawled? It seems that the slug won't be resolved anyways - which is correct because it shouldn't be live when created in workspace. So, there is no page to be shown and therefore workspace records can be excluded from the crawl process.

**Comment by medarob** [comment]
On second thought, the 2nd question might be a problem from the sitemap 🤔 and not sitecrawler. Sitecrawler just uses the URL which is in the sitemap... so, the error seems to be there. 😅

**Comment by schliesser** [comment]
Hey @medarob 
thanks for trying the extension!

The logic in the sitecrawler ist very simple: All urls which do not return the status code 200 have some errors (e.g. 404 / 500) and should be excluded from the sitemap. But:

1. Empty detail pages
I'm aware of the issues with the empty detail pages. They normally return a 404 status code instead of 200, which is correct. Even when they don't redirect you to your global 404 page. You can validate this in the developer tools or with browser plugins:
![image](https://user-images.githubusercontent.com/11655823/165230422-d3738a9f-5e1a-4692-bce7-3e41405f6667.png)

IMHO the empty detail page shouldn't be in the sitemap in the first place, because other crawlers (Google Bot) are also crawling the page for no reason. But I haven't found a solution with standard TYPO3 settings to prevent this. If you disable the page for robots, then all the valid news pages are also excluded...

2. Workspaces
As you mentioned, workspace related pages and records (news, events,...) shouldn't be in the sitemap.xml at all. They are not reachable for users without a backend-user session.
I have no project using workspaces, but I wonder if the issue only for records? Are pages which are only in a workspace available also listed in the sitemap? Or does it only happen for news, events,...?
Maybe you can dig a little bit into this issue and may create a bugreport here: https://forge.typo3.org/projects/typo3cms-core/issues

**Comment by medarob** [comment]
Thank you for your reply.
Regarding the workspace issue, it seems that this was already fixed: https://forge.typo3.org/projects/typo3cms-core/repository/1749/revisions/37b7a893359f060c17261afdfa6f4bdcec571087

I had the additional code missing in my RecordXmlSitemap. Adding the above fix to our own RecordXmlSitemap seems to fix the problem and no workspace records are shown now in the sitemap.xml.
